### PR TITLE
Add scripts, documentation, and entrypoint to allow the build image to run

### PR DESCRIPTION
**Pull request by rickyrockrat**
Hi,
I just spent several hours getting this to run on my older system. I thought this might be useful for other to get the latest OpenSCAD running.
Thanks

### CODE REVIEW

**Comment by t-paul** [comment]
What system are you trying to run this on? The scripts are mostly part of the CI infrastructure which is why they are not meant to run OpenSCAD inside that container at this point. Plain docker seems to be not ideal for running OpenSCAD, AppImage / Flatpak / Snap are more focussed on running GUI applications.

That said, it would be nice to have a generally useful base image for running headless OpenSCAD. So making it work for both szenarios would be great.

**Comment by rickyrockrat** [comment]
A Debian-based jessie system. I know, it's old and I am looking for a new distro at this point.
The runXme runs the gui fine on my system. For me, at least, it was a matter of docker build, then executing that script I created. 

What would you like to have different?

**Comment by rickyrockrat** [comment]
It would be pretty trivial to have it ask the user if you want the shell or use the GUI instead. 
The existing ENTRYPOINT in the Dockerfile is not useful in any way I can tell - tar fails in lots of interesting ways.

**Comment by t-paul** [comment]
Right, jessie is just about too old to run the other binaries, at least AppImage and Snap (not sure about Flatpak). The currently supported baseline of the pre-built stuff is Ubuntu 16.04 which has slightly newer things compared to jessie.

I have not tested it yet, but the script looks ok as such. I need to verify there's not automation relying on the `tar` entry point. Keeping [all that](https://github.com/openscad/openscad/wiki/CI-Setup) running is pretty important as we don't have a big team standing by to update/fix things. If it's only my local scripts, I just need to find the time to update those.

**Comment by rickyrockrat** [comment]
Not a problem. Just thought it would be nice for other folks to be able to run the latest. I'm thinking I should add notes on how to build a specific version so someone could modify the Dockerfile to build whatever.  Thanks for building such a great application.

**Comment by t-paul** [comment]
We can't change the CI base images, but now separate images are published on https://hub.docker.com/repository/docker/openscad/openscad

**Pull request closed without merging**
